### ISSUE TITLE
Farsi Support & Presentation Forms A?

### ISSUE THREAD

**Issue by noblemaster** [eloraiby/arabtype#3]
I am successfully using your library. It works great - Thanks :)

I wonder, would it be possible to add support for Farsi? I tried to render Farsi text, but the glyphs don't appear correctly connected? I believe part of the Presentation Form A characters would to be used? How difficult would that be to add? Is it possible?

**Comment by eloraiby** [comment]
My guess that depends on the font been used, but it shouldn't be hard to add. I will take a look on it soon and estimate the work needed.

**Comment by noblemaster** [comment]
Thanks! I am using Arial MS Unicode which appears to have most if not all the letters needed, i.e. the Arabic Presentation Forms A. What I am not so sure about is if all the letters in Presentation Forms A are needed? I assume just a subset might be fine?

I checked Wikipedia & some other sites, but it's difficult to find much information about how to use those forms etc. 

Anyhow, thanks for looking into it! :)

**Comment by noblemaster** [comment]
Anyhow, I managed to integrate the following and it appears to be working:
https://github.com/font-store/persian-reshaper/blob/master/js/persian-script-reshaper.js
