### ISSUE TITLE
Does this work with combination of Arabic and Latin characters ?

### ISSUE THREAD

**Issue by KIRTKUNA2** [eloraiby/arabtype#4]
Consider a sequence of <Arabic><Latin><Arabic> characters.  Will this work for R-L for such combination of characters ?
Example
![image](https://user-images.githubusercontent.com/30593653/28774946-4653e924-760d-11e7-90fd-0c7c3c3793c2.png)

**Comment by KIRTKUNA2** [comment]
The above is the snapshot from MS Word. If I type the same in the text box I get the following
مرحبا يا صديقي120E كيف حالك

**Comment by noblemaster** [comment]
This library converts Arabic characters into their corresponding presentation forms. The resulting string produced here is ready for rendering. However this library does not have a render component. 

When you render the text, e.g. using a bitmap font, your rendering loop will have to make sure to correctly render LTR or RTL. To answer your question, yes, it works in combination with Arabic & Latin characters, but your renderer has to to take care of actually render the characters correctly.

**Comment by eloraiby** [comment]
exactly what @noblemaster pointed out. The library has no notion of LTR/RTL.
